#import "@/graphql/fragments/Image.gql"
#import "@/graphql/fragments/MenuItem.gql"

query GetNavigationMenu {
	NavigationMenu {
		logo {
			...Image
		}
		alternateLogo {
			...Image
		}
		routes {
			id
		}
	}
}
